### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Ashrafmdmatin41** [devgaganin/Save-Restricted-Content-Bot-Repo#10]
![Screenshot_20240613_221310](https://github.com/devgaganin/Save-Restricted-Content-Bot-Repo/assets/91468485/6b73b75c-7c94-4733-abea-f9ce1917a94d)
![IMG_20240613_221304_557](https://github.com/devgaganin/Save-Restricted-Content-Bot-Repo/assets/91468485/b18b0370-d530-482e-bfe2-64846f11e26f)

**Comment by devgaganin** [comment]
Change format

**Comment by MatizTechz** [comment]
> Change format

Hmm right
