### ISSUE TITLE
not able to deply on koyeb

### ISSUE THREAD

**Issue by kkhan31** [devgaganin/Save-Restricted-Content-Bot-Repo#16]
Getting Below error

![image](https://github.com/devgaganin/Save-Restricted-Content-Bot-Repo/assets/126147161/1e10c3d6-e669-407a-a3f0-2d3fa6df90c9)

**Comment by SudoR2spr** [comment]
Not a single branch koyeb is working ❌

**Comment by SudoR2spr** [comment]
Using this repo means wasting time. 

I have to say sorry. This repo I've been trying to deploy for a few hours.  But the bot was not successful. Publish your repo after its successful for complete. Or make it private. Annoy people

**Comment by devgaganin** [comment]
> Using this repo means wasting time.
> 
> I have to say sorry. This repo I've been trying to deploy for a few hours. But the bot was not successful. Publish your repo after its successful for complete. Or make it private. Annoy people

See our tutorial on telegram/better you don't change the dockerfile

On the other hand the instance stopped is not the repo error it is Koyeb's it could not identify it as healthy.
The possible cause is you are a FreeBie of Koyeb and trying to deploy on Koyeb so I suggest deploy as worker.
