### ISSUE TITLE
Not a single branch koyeb is working ❌

### ISSUE THREAD

**Issue by SudoR2spr** [devgaganin/Save-Restricted-Content-Bot-Repo#17]
Using this repo means wasting time.

Not a single branch koyeb is working ❌

I have to say sorry. This repo I've been trying to deploy for a few hours. But the bot was not successful. Publish your repo after its successful for complete. Or make it private. Annoy people

**Comment by devgaganin** [comment]
Dont change dockerfile keep it as it is
