### ISSUE TITLE
/setchat not working

### ISSUE THREAD

**Issue by hhsw2015** [devgaganin/Save-Restricted-Content-Bot-Repo#5]
i uset /setchat to set to my public channel ID

after the file be download with /dl youtubeurl , the message not forward to my public channel

**Comment by Ashrafmdmatin41** [comment]
> i uset /setchat to set to my public channel ID
> 
> after the file be download with /dl youtubeurl , the message not forward to my public channel

Brother send logs too

**Comment by hhsw2015** [comment]
i use you bot , i am not host it,

it output 
Chat ID set successfully!

then i use /dl command

**Comment by devgaganin** [comment]
> i uset /setchat to set to my public channel ID
> 
> after the file be download with /dl youtubeurl , the message not forward to my public channel

This is not an issue bro...
Make bot admin in your channel and use `/dl ` command with link directly in channel or group.

Later I will add forward to channel if /dl command used in private and user have set thier chat 🆔 via /setchat.

**Comment by devgaganin** [comment]
actually the setchat was not for /dl will add it

On 2024-06-07 04:41, Jill Kok, San Mou wrote:

> i uset /setchat to set to my public channel ID
> 
> after the file be download with /dl youtubeurl , the message not 
> forward to my public channel
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you are subscribed to this 
> thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/devgaganin/Save-Restricted-Content-Bot-Repo/issues/5
[2]
