### ISSUE TITLE
Batch command

### ISSUE THREAD

**Issue by Ashrafmdmatin41** [devgaganin/Save-Restricted-Content-Bot-Repo#6]
![IMG_20240608_105042_521](https://github.com/devgaganin/Save-Restricted-Content-Bot-Repo/assets/91468485/c3b7a4e2-2b62-44c8-b5e0-32e0a124198a)
- Range must be an integer!
- by default your thumbnail was not set on video so better is to remove default thumbnail
- - Range must be an integer! (Only saving only 1 last content not all)
- - why start downloading content even save restricted is off on private channel

**Comment by devgaganin** [comment]
See tutorial, how to use to use commands you are giving link in when it is asking the number of files it is good to read what the bot is expecting so instead of  link you must put the number of files eg.  100, 200, etc.
Tutorial link is - https://t.me/devggn/28

Second: Thumbnail Issue ?
If you are using Heroku or any other external managed environment install ffmpeg build pack by going to setting and add build pack and then paste ffmpeg build pack link (for heroku it is `https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.git` )

If you on VPS then install ffmpeg via pip 
`pip install ffmpeg`

Thanks!

**Comment by Ashrafmdmatin41** [comment]
> See tutorial, how to use to use commands you are giving link in when it is asking the number of files it is good to read what the bot is expecting so instead of link you must put the number of files eg. 100, 200, etc. Tutorial link is - https://t.me/devggn/28
> 
> Second: Thumbnail Issue ? If you are using Heroku or any other external managed environment install ffmpeg build pack by going to setting and add build pack and then paste ffmpeg build pack link (for heroku it is `https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.git` )
> 
> If you on VPS then install ffmpeg via pip `pip install ffmpeg`
> 
> Thanks!

Ok about batch i understand but about thumbnail understand what i did first created app on heroku settings then added alll variable then i connect the app with git and deployed so i think i did right

**Comment by devgaganin** [comment]
i think these issues are now fixed ...
added the handlers for public channel (no download for public channel)
public group / topic enabled group now supported just via post link
forwarding in topics is now accessible

On 2024-06-08 10:58, Md Matin Ashraf wrote:

> IMG_20240608_105042_521.jpg (view on web) [1]
> 
> * Range must be an integer!
> * by default your thumbnail was not set on video so better is to remove 
> default thumbnail
> 
> *
> 
> * Range must be an integer! (Only saving only 1 last content not all)
> 
> *
> 
> * why start downloading content even save restricted is off on private 
> channel
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you are subscribed to this 
> thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/devgaganin/Save-Restricted-Content-Bot-Repo/assets/91468485/c3b7a4e2-2b62-44c8-b5e0-32e0a124198a
[2] 
https://github.com/devgaganin/Save-Restricted-Content-Bot-Repo/issues/6
[3]
