### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Ashrafmdmatin41** [devgaganin/Save-Restricted-Content-Bot-Repo#9]
![Screenshot_20240611_180424](https://github.com/devgaganin/Save-Restricted-Content-Bot-Repo/assets/91468485/0b9ec72e-f665-482b-9d10-36601605734c)

- cancel command not working
- can you add modules for custom caption like 
{file_duration} - Duration of the file
{file_name} - Name of the file
{file_size} - Size of the file
{file_extension} - Extension of the file
And any text to add on custom caption

**Comment by devgaganin** [comment]
Later
